_BASE_: /home/zyl/fast-reid/configs/osnet/Base-MGN.yml

MODEL:
  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN
    DEPTH: 34x
    LAST_STRIDE: 1
    FEAT_DIM: 512
    WITH_IBN: True
    PRETRAIN: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/mgn_R50-ibn
