_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
   DEPTH: 50x
   FEAT_DIM: 2048
DATASETS:
  NAMES: ("MS1MV2_V1",)
  TESTS: ("MS1MV2_V1",)
INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 2
  NUM_WORKERS: 4
SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/face/bagtricks_R50_V1
